version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: controle_financas_db
    restart: always
    environment:
      POSTGRES_DB: controleFinancas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: ./ApiFinancial
      dockerfile: Dockerfile
    container_name: controle_financas_api
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__FinancasDbContext: Host=postgres;Port=5432;Database=controleFinancas;Username=postgres;Password=postgres
    ports:
      - "5132:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: controle_financas_front
    depends_on:
      - api
    ports:
      - "5173:5173"

volumes:
  postgres_data: